// Export utilities for PropPulse data

export function exportToCSV(data: Record<string, any>[], filename: string) {
    if (!data.length) return;

    const headers = Object.keys(data[0]);
    const csvRows = [
        headers.join(','),
        ...data.map((row) =>
            headers
                .map((h) => {
                    const val = row[h];
                    // Escape commas and quotes
                    const str = String(val ?? '');
                    return str.includes(',') || str.includes('"')
                        ? `"${str.replace(/"/g, '""')}"`
                        : str;
                })
                .join(',')
        ),
    ];

    const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
    downloadBlob(blob, `${filename}.csv`);
}

export function exportToJSON(data: any, filename: string) {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    downloadBlob(blob, `${filename}.json`);
}

export async function exportToPDF(elementId: string, title: string) {
    // We use the browser's print-to-PDF capability
    const el = document.getElementById(elementId);
    if (!el) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
        alert('Please allow popups to export PDF');
        return;
    }

    printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>${title} — PropPulse Report</title>
            <style>
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap');
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body {
                    font-family: 'Inter', sans-serif;
                    color: #1a1f35;
                    padding: 40px;
                    background: white;
                }
                h1 { font-size: 24px; margin-bottom: 8px; }
                .report-meta { color: #64748b; font-size: 12px; margin-bottom: 32px; }
                table { width: 100%; border-collapse: collapse; margin-top: 16px; }
                th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
                th { font-weight: 700; color: #475569; text-transform: uppercase; font-size: 11px; letter-spacing: 0.05em; background: #f8fafc; }
                .positive { color: #10b981; }
                .negative { color: #ef4444; }
                .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
            </style>
        </head>
        <body>
            <h1>📊 ${title}</h1>
            <div class="report-meta">
                Generated by PropPulse · ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </div>
            ${el.innerHTML}
            <div class="footer">
                PropPulse — US Real Estate Trends & Analytics · Data sourced from Zillow Research, FRED & public records.
            </div>
        </body>
        </html>
    `);

    printWindow.document.close();
    setTimeout(() => {
        printWindow.print();
    }, 500);
}

function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
